### ISSUE TITLE
No Service Selection

### ISSUE THREAD

**Issue by martiko70** [bashGroup/node-red-contrib-fritz#45] opened 2020-03-31 09:57 UTC
Hi,
I am already using some Flows with contrb-fritz and they work fine, also the copied examples do work.

But when I add a new Frritz!Box node to my Flow (and select the already configured Configuratio-Node, which works fine for the existing Flows), the drop down List for the Service Selection remains empty (there is just a grey line in the drop down list)

Any Idea how to solve this issue?

**Comment by e-lange** [comment] 2020-04-24 06:49
Hello all,

I can fully reproduce this issue. Is there anything to support solving this issue?
Does anybody happen to have a work-arouond for this?

Somehow this renders the node unusable...

Thanks

**Comment by solick** [comment] 2020-09-25 19:01
Hi i can confirm this bug. Is this project still under maintenance?

**Comment by mapero** [comment] 2020-09-26 20:01
Duplicate of #43

**Closed** 2020-09-29 20:44 UTC
Labels: bug
