### ISSUE TITLE
Which arguments must be passed?

### ISSUE THREAD

**Issue by funker** [bashGroup/node-red-contrib-fritz#37] opened 2019-10-10 20:39 UTC
Hey guys,

I'm currently trying to read some information from my FB6490 Cable with these nodes.

I configured the config node and inserted an fritzbox-in node as follows:

> Service "urn:dslforum-org:service:WANIPConnection:1"

> Action "GetExternalIPAddress"

Now I read, that I have to pass arguments to the node, but the node itself does not give any hint, which arguments must be passed. 
The info box only says 

> Use the msg.payload to pass the arguments in the form of. Required arguments are: {}

When I pass the output to a Debug node it says

> TypeError: Cannot read property 'actions' of undefined

The next thing I would like to get is the TotalBytesSent and TotalBytesReceived values, but I have the same output.

I was not able to find any documentation about that either. 
Could anyone help please?

Thanks in advance.

**Comment by pinguinpfleger** [comment] 2019-10-18 12:50
> TypeError: Cannot read property 'actions' of undefined
Got the same when SSL is enabled

**Comment by LennyPenny** [comment] 2020-01-13 23:00
In your device config you need to change the port of to `49443`. 
The default `49000` is for non ssl connections :)

**Comment by P1Rebo** [comment] 2020-09-26 20:29
Duplicate of #50. Will be fixed soon.

**Comment by P1Rebo** [comment] 2020-09-26 20:30
Duplicate of #50. Will be fixed soon. Issue will be closed.

**Closed by P1Rebo** 2020-09-26 20:30 UTC
